name: DemoApp
options:
  bundleIdPrefix: com.demo
  deploymentTarget:
    iOS: "15.0"
packages:
  AppStoreConnect:
    path: ..
targets:
  DemoApp:
    type: application
    platform: iOS
    sources:
      - DemoApp
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.demo.DemoApp
    dependencies:
      - package: AppStoreConnect
